### ISSUE TITLE
A simple suggestion about Project 2 

### ISSUE THREAD

**Issue by yuchenlin** [chasingegg/SJTU_OS-project#1]
Hi, Gao

Great work and professional reports!

Here is a simple suggestion. I noticed that you used an array to save and process the history commands, which will cause low-efficiency from my perspective. Users are very likely to execute more than 10 commands and thus from the 11th command, your program will move the first 9 history commands every time. Maybe linked list is a better choice in this scenario. 

Looking forward to your future repos. Keep chasing on the way~ Ha!

**Comment by chasingegg** [comment]
Hello, Lin (we are both SJTUers 😄)

Thank you for your issues! 

I reviewed my code just now, actually I didn't consider this problem which will cause low-efficiency. I think I can use the array as a circle(use mod operation), and define an variable to record the start index.  And linked list you recommend is also a good choice, but we also need index to record the position to do the deletion, or it may also cause low-efficiency problem.

Thank you again! I will pay attention to your repos constantly. Keep on going!

**Comment by yuchenlin** [comment]
Yes, circular queue is indeed a better idea.

Haha, seems that you are a member of BCMI. Actually, I've been developing a website based on Django for collecting sentimental videos for BCMI recently. 😝
